name: ci-tags-date

on:
  push:
    tags:
    # E.g. 20210402.0.0
    - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  windows-2016:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Display system info (windows)
      run: |
        Set-StrictMode -Version Latest; $ErrorActionPreference = 'Stop'
        hostname
        whoami
        systeminfo
        Get-PSDrive
        Get-Location
        # pwsh version
        $PSVersionTable
        # Windows Powershell version?
        powershell -Command '$PSVersionTable'
  windows-2019:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Display system info (windows)
      run: |
        Set-StrictMode -Version Latest; $ErrorActionPreference = 'Stop'
        hostname
        whoami
        systeminfo
        Get-PSDrive
        Get-Location
        # pwsh version
        $PSVersionTable
        # Windows Powershell version?
        powershell -Command '$PSVersionTable'
  ubuntu-16-04:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Display system info (linux)
      run: |
        set -e
        hostname
        whoami
        cat /etc/*release
        lscpu
        free
        df -h
        pwd
        docker info
        docker version
  macos-10-15:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Display system info (macos)
      run: |
        set -e
        hostname
        whoami
        df -h
        pwd
        # docker info
        # docker version


  ##########
  # Docker #
  ##########
  test-powershell-6-0:
    runs-on: ubuntu-16.04
    container:
      # image: theohbrothers/docker-powershell:6.0.2-ubuntu-16.04-git
      image: mcr.microsoft.com/powershell:6.0.2-ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Display system info (linux)
      run: |
        set -e
        hostname
        whoami
        cat /etc/*release
        lscpu
        free
        df -h
        pwd
    - name: Powershell version
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: Test
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command './test/test.ps1'

  test-powershell-6-1:
    runs-on: ubuntu-16.04
    container:
      # image: theohbrothers/docker-powershell:6.1.3-alpine-3.8-git
      image: mcr.microsoft.com/powershell:6.1.3-alpine-3.8
    steps:
    - uses: actions/checkout@v2
    - name: Display system info (linux)
      run: |
        set -e
        hostname
        whoami
        cat /etc/*release
        # lscpu
        free
        df -h
        pwd
    - name: Powershell version
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: Test
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command './test/test.ps1'

  test-powershell-6-2:
    runs-on: ubuntu-16.04
    container:
      # image: theohbrothers/docker-powershell:6.2.4-alpine-3.8-git
      image: mcr.microsoft.com/powershell:6.2.4-alpine-3.8
    steps:
    - uses: actions/checkout@v2
    - name: Display system info (linux)
      run: |
        set -e
        hostname
        whoami
        cat /etc/*release
        # lscpu
        free
        df -h
        pwd
    - name: Powershell version
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: Test
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command './test/test.ps1'

  test-powershell-7-0:
    runs-on: ubuntu-16.04
    container:
      # image: theohbrothers/docker-powershell:7.0.3-alpine-3.9-20200928
      image: mcr.microsoft.com/powershell:7.0.3-alpine-3.9
    steps:
    - uses: actions/checkout@v2
    - name: Display system info (linux)
      run: |
        set -e
        hostname
        whoami
        cat /etc/*release
        # lscpu
        free
        df -h
        pwd
    - name: Powershell version
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: Test
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command './test/test.ps1'

  test-powershell-7-1:
    runs-on: ubuntu-16.04
    container:
      # image: theohbrothers/docker-powershell:7.1.3-alpine-3.11-20210316-git
      image: mcr.microsoft.com/powershell:7.1.3-alpine-3.11-20210316
    steps:
    - uses: actions/checkout@v2
    - name: Display system info (linux)
      run: |
        set -e
        hostname
        whoami
        cat /etc/*release
        # lscpu
        free
        df -h
        pwd
    - name: Powershell version
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: Test
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command './test/test.ps1'

  test-powershell-7-2:
    runs-on: ubuntu-16.04
    container:
      # image: theohbrothers/docker-powershell:7.2.0-preview.4-alpine-3.11-20210316-git
      image: mcr.microsoft.com/powershell:7.2.0-preview.4-alpine-3.11-20210316
    steps:
    - uses: actions/checkout@v2
    - name: Display system info (linux)
      run: |
        set -e
        hostname
        whoami
        cat /etc/*release
        # lscpu
        free
        df -h
        pwd`
    - name: Powershell version
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: Test
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command './test/test.ps1'

  publish-draft-release:
    needs: [windows-2016, windows-2019, ubuntu-16-04, macos-10-15, test-powershell-6-0, test-powershell-6-1, test-powershell-6-1, test-powershell-7-0, test-powershell-7-1, test-powershell-7-2]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      # - name: Set REF environment variable
      #   run: |
      #     REF=$( echo "${GITHUB_REF}" | rev | cut -d '/' -f 1 | rev )
      #     echo "REF=$REF" >> $GITHUB_ENV
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: toolmantim/release-drafter@v5.2.0
        with:
          publish: true
          # tag: ${{ env.REF }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
